common: &COMMON
  env:
    RUSTFLAGS: -Dwarnings
    RUSTDOCFLAGS: -Dwarnings
  cargo_cache:
    folder: $CARGO_HOME/registry
  build_script:
    - cargo build $CARGO_ARGS
  doc_script:
    - cargo doc $CARGO_ARGS --no-deps


task:
  name: MSRV
  container:
    image: rust:1.45.0
  env:
    # CARGO_NET_GIT_FETCH_WITH_CLI is only necessary with Rust 1.45
    CARGO_NET_GIT_FETCH_WITH_CLI: true
  << : *COMMON
  before_cache_script: rm -rf $CARGO_HOME/registry/index

task:
  name: stable
  container:
    image: rust:latest
  << : *COMMON
  test_script:
    # Mockall has unit tests in the examples, so we must pass --all-targets
    - cargo test $CARGO_ARGS --all-targets
  before_cache_script: rm -rf $CARGO_HOME/registry/index

task:
  name: nightly
  container:
    image: rustlang/rust:nightly
  env:
    CARGO_ARGS: --all-features
  << : *COMMON
  test_script:
    # Mockall has unit tests in the examples, so we must pass --all-targets
    - cargo test $CARGO_ARGS --all-targets
  lint_script:
    - rustup component add clippy
    - cargo clippy $CARGO_ARGS --all-targets --workspace -- -D warnings
  reproducibility_script:
    - env RUSTFLAGS="--cfg reprocheck" cargo check $CARGO_ARGS --all-targets
  minver_script:
    - cargo update -Zminimal-versions
    - cargo test $CARGO_ARGS
  before_cache_script: rm -rf $CARGO_HOME/registry/index
